# Generated by Django 3.0.4 on 2020-03-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.IntegerField(choices=[(0, 'Choose Topic'), (1, 'World'), (2, 'Technology'), (3, 'Design'), (4, 'Culture'), (5, 'Business'), (6, 'Politics'), (7, 'Opinion'), (8, 'Science'), (9, 'Health'), (10, 'Style'), (11, 'Travel'), (12, 'Life')], default=0)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
            ],
        ),
    ]
