# Generated by Django 3.0.4 on 2020-03-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_by_user', '0002_auto_20200326_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='topic',
            field=models.CharField(choices=[('', 'Choose Topic'), ('World', 'World'), ('Technology', 'Technology'), ('Design', 'Design'), ('Culture', 'Culture'), ('Business', 'Business'), ('Politics', 'Politics'), ('Opinion', 'Opinion'), ('Science', 'Science'), ('Health', 'Health'), ('Style', 'Style'), ('Travel', 'Travel'), ('Life', 'Life')], default=0, max_length=200),
        ),
    ]
