# Generated by Django 3.0.4 on 2020-03-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_by_user', '0003_auto_20200327_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views_total',
            field=models.IntegerField(default=1),
        ),
    ]
