# Generated by Django 3.0.4 on 2020-03-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_by_user', '0004_blog_views_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-views_total']},
        ),
    ]
